defaultEntryPoints = ["http"]

[log]
  level = "DEBUG"

[web]
# Port for the status page
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":9393"

[file]
[frontends]
  [frontends.sampleavatar]
  backend = "sampleavatar"
  entrypoints = ["http"]
    [frontends.sampleavatar.routes.test_1]
    rule = "PathPrefixStrip:/sample/"
  [frontends.samplenc]
  backend = "samplenc"
  entrypoints = ["http"]
    [frontends.samplenc.routes.test_1]
    rule = "PathPrefixStrip:/sample/nc"

[backends]
  [backends.sampleavatar]
    [backends.sampleavatar.servers.server1]
    url = "http://192.168.1.109:64101"
  [backends.samplenc]
    [backends.samplenc.servers.server1]
    url = "http://192.168.1.109:64103"