defaultEntryPoints = ["http"]

[log]
  level = "DEBUG"

[web]
# Port for the status page
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":9393"

[file]
[frontends]
  [frontends.sample]
  backend = "sample"
  entrypoints = ["http"]
    [frontends.sample.routes.test_1]
    rule = "Host:sample.eb.neurul.net"

[backends]
  [backends.sample]
    [backends.sample.servers.server1]
    url = "http://192.168.1.110:64001"