version: '3'

services:   
  identity.api:
    image: ei8works/identity.api:0.1.7
    env_file:
      - ./variables.env
    expose:
      - "80"
    ports:
      - ${HOST_IP}:${HOST_PORT}:80
    volumes:
      - ./:/C/db